stages:
- build-jekyll
- build-npm
- deploy

build-jekyll:
  stage: build-jekyll
  image: jekyll/jekyll:3.8
  before_script:
  - bundle
  script:
  - bundle exec jekyll build
  artifacts:
    paths:
    - _site/

build-npm:
  stage: build-npm
  image: node:9
  before_script:
  - npm install
  script:
  - npx webpack --output-path _site/assets/
  artifacts:
    paths:
    - _site/

deploy:
  stage: deploy
  image: python:latest
  before_script:
  - pip install awscli
  script:
  - aws s3 cp _site/ s3://$S3_BUCKET_NAME/ --recursive
  after_script:
  - rm -r _site
